### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by LemoFire** [diadal/vue3-qr-code-styling#1]
```
Module parse failed: Unexpected token (96:16)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader-v16/dist/index.js
You may need an additional loader to handle the result of these loaders.
|     console.log('props', props)
|     const fileExt = ref<string>(props.fileExt)
>     const qrCode: QRCodeStyling = new VQRCodeStyling({
|       width: props.width,
|       height: props.height,

 @ ./node_modules/vue3-qr-code-styling/src/vue3-qr-code-styling.vue?vue&type=script&lang=ts 1:0-165 1:0-165 1:166-320 1:166-320
 @ ./node_modules/vue3-qr-code-styling/src/vue3-qr-code-styling.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/common/qrcode/QRCode.vue?vue&type=script&lang=ts
 @ ./src/components/common/qrcode/QRCode.vue?vue&type=script&lang=ts
 @ ./src/components/common/qrcode/QRCode.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/Home.vue?vue&type=script&lang=js
 @ ./src/views/Home.vue?vue&type=script&lang=js
 @ ./src/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.221:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by diadal** [comment]
have not implemented that download the use directly from your components 

<img width="294" alt="Screen Shot 2021-04-08 at 8 06 24 PM" src="https://user-images.githubusercontent.com/19895516/114082695-f3aa9280-98a5-11eb-8079-645ffcd3e1f0.png">

then follow the rest of readme it work great

**Comment by diadal** [comment]
the `src` content only

**Comment by wattsie** [comment]
Hi, weird I get the same issue.

Using Laravel 8, Vue 3

Did the `npm install` as per doc.

Created a component called `VueQr3` and added example code snippet.

As soon as I import this new component into any Vue, it gives the same error above.

Do you need to adjust the `webpack` config to handle?

Any suggestions?

Might be nice to be able to simply (something like):
```
import Vue3QrCode from 'vue3-qr-code-styling'

then

<vue3-qr-code ...options... >
</vue3-qr-code>

```


Cheers.

**Comment by diadal** [comment]
download the component directly you can't use npm or yarn for now very busy with other project i will add the package to npm soon once am less busy 
```
 components: {
    VueQr3: defineAsyncComponent(() =>
      Promise.resolve(import('components/vue3-qr-code-styling'))
    )
  },
```
or 
`import Vue3QrCode from 'components/vue3-qr-code-styling'`

**Comment by diadal** [comment]
<img width="319" alt="Screen Shot 2021-05-18 at 7 25 23 AM" src="https://user-images.githubusercontent.com/19895516/118602167-4121f580-b7aa-11eb-8a13-69303def3215.png">

**Comment by diadal** [comment]
try this `npm install vue3-qr-code-styling `

**Comment by diadal** [comment]
working 

```
 


<VueQr3
              :width="800"
              :height="800"
            ....
            ></VueQr3>
```

**Comment by diadal** [comment]
if any other issue you can reopen

**Comment by wattsie** [comment]
Hey, thanks for your help.

Ok, I see you just pushed a new version. It just updated `"vue3-qr-code-styling": "^1.4.5"`.

So, still getting the same issue when I create a component with the code snippet.

Do I still need to copy the `src` folder into a local components folder?

Not sure why it doesn't like this line `const qrCode: QRCodeStyling = new VQRCodeStyling({`

Cheers.

**Comment by diadal** [comment]
if you downloaded the package create folder named `vue3-qr-code-styling` in your  `component` folder then copy all content in dowloaded `src` to `components/vue3-qr-code-styling` done it work 

```
components: {
    VueQr3: defineAsyncComponent(() =>
      Promise.resolve(import('components/vue3-qr-code-styling'))
    )
  }

``

**Comment by diadal** [comment]
if error share your code and send a screenshot of vue3-qr-code-styling in your component

**Comment by LaravDev** [comment]
I did it as you explain here, but still, not working... i'm using Vue3 with script setup with typescript, could that be the reason? any incompatibility?
