### ISSUE TITLE
Failed to resolve component: VueQr3 

### ISSUE THREAD

**Issue by LaravDev** [diadal/vue3-qr-code-styling#2]
Hi, first than all, this looks very awesome, thanks for the wrapper...

I have tried to import just as stated in the documentation, but I get the following error: **Failed to resolve component: VueQr3**

this is the piece of code related:

```
<script setup lang="ts">
import {defineComponent, defineAsyncComponent, defineEmit, defineProps, ref} from 'vue'
import { Notyf } from 'notyf';
const notyf = new Notyf({
  duration: 2000,
  position: {
    x: 'center',
    y: 'bottom',
  },
})
import store from '/@src/store/index';
import { parseDate, reservationRoomTotalPax, decodeCountry, decodeLoyaltyLevel, decodeManualCheckinReason, tooltipConditions } from "/@src/utils/helpers";

defineComponent({
  // name: "Login",
  components: {
    VueQr3: defineAsyncComponent(() =>
      Promise.resolve(import('vue3-qr-code-styling'))
    )
  }
})
```

Any hints?

**Comment by diadal** [comment]
you need to download the package then used it from your componet

**Comment by diadal** [comment]
try this `npm install vue3-qr-code-styling `

**Comment by diadal** [comment]
working now
<VueQr3
              :width="800"
              :height="800"
            ....
            ></VueQr3>

**Comment by diadal** [comment]
if any other issue you can reopen

**Comment by LaravDev** [comment]
I've tried downloading and importing directly to my components, but still doesn't work, also tried from npm, but same result. is it possible to explain step by step how to import and use it? 

Thanks in advance

**Comment by diadal** [comment]
check this https://github.com/diadal/vue3-qr-code-styling/issues/1

**Comment by clinsted** [comment]
I was having the same issue and ended up using a fork of this project, by user scholtz, where the issue has been fixed: https://github.com/scholtz/qrcode-vue3
